// ─── Brevo (formerly Sendinblue) Email Service ───
// Uses Brevo's HTTP API directly with Node's built-in fetch — no extra packages needed.
// Free tier: 300 emails/day, sends to ANY email address (no custom domain required).

// ─── Convert markdown-style text to basic HTML ───
// The AI returns markdown (with **bold**, ## headers, - bullets).
// This function converts it into HTML so the email looks nice.
const markdownToHtml = (text) => {
  return text
    // Convert **bold** to <strong>
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Convert ## headers to <h3>
    .replace(/^### (.*$)/gm, '<h3 style="color: #1a1a2e; margin-top: 16px;">$1</h3>')
    .replace(/^## (.*$)/gm, '<h2 style="color: #1a1a2e; margin-top: 20px;">$1</h2>')
    .replace(/^# (.*$)/gm, '<h1 style="color: #1a1a2e; margin-top: 24px;">$1</h1>')
    // Convert bullet points (- item) to list items
    .replace(/^- (.*$)/gm, '<li style="margin-bottom: 4px;">$1</li>')
    // Wrap consecutive <li> items in <ul>
    .replace(/(<li.*<\/li>\n?)+/g, '<ul style="padding-left: 20px; margin: 8px 0;">$&</ul>')
    // Convert numbered lists (1. item) to list items
    .replace(/^\d+\.\s(.*$)/gm, '<li style="margin-bottom: 4px;">$1</li>')
    // Convert newlines to <br> for spacing
    .replace(/\n/g, '<br>');
};

// ─── Send the sales summary email via Brevo API ───
// Takes: recipient email address + AI-generated summary text
// Returns: the Brevo API response
const sendEmail = async (toEmail, summary) => {
  // Convert the markdown summary to HTML
  const summaryHtml = markdownToHtml(summary);

  // ─── Build a professional HTML email template ───
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f8; font-family: Arial, Helvetica, sans-serif;">
      <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">

        <!-- Header -->
        <div style="background-color: #1a1a2e; padding: 24px 32px; text-align: center;">
          <h1 style="color: #ffffff; margin: 0; font-size: 22px;">Sales Insight Report</h1>
          <p style="color: #a0a0b8; margin: 8px 0 0; font-size: 14px;">Generated by Sales Insight Automator</p>
        </div>

        <!-- Body -->
        <div style="padding: 32px; color: #333333; font-size: 15px; line-height: 1.6;">
          ${summaryHtml}
        </div>

        <!-- Footer -->
        <div style="background-color: #f4f4f8; padding: 16px 32px; text-align: center; font-size: 12px; color: #888888;">
          <p style="margin: 0;">This report was auto-generated by <strong>Sales Insight Automator</strong> powered by Rabbitt AI.</p>
          <p style="margin: 4px 0 0;">Powered by Groq (Llama 3) &bull; Delivered via Brevo</p>
        </div>

      </div>
    </body>
    </html>
  `;

  // ─── Send via Brevo's REST API ───
  const response = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      'accept': 'application/json',
      'api-key': process.env.BREVO_API_KEY,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      sender: {
        name: 'Sales Insight Automator',
        email: process.env.BREVO_SENDER_EMAIL,  // your Brevo-verified email
      },
      to: [{ email: toEmail }],
      subject: 'Your Sales Insight Report is Ready',
      htmlContent: htmlContent,
    }),
  });

  // Parse the response
  const data = await response.json();

  // Check for errors
  if (!response.ok) {
    throw new Error(`Email failed to send: ${data.message || 'Unknown Brevo error'}`);
  }

  return data;
};

module.exports = { sendEmail };
